

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/mock-api/:splat"
  status = 200
  force = true

[functions]
  directory = "functions"
[build]
  command = "ng build --prod"
  publish = "dist/abc-dashboard/browser"

[[plugins]]
  package = "@netlify/angular-runtime"