

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/mock-api/:splat"
  status = 200
  force = true

[functions]
  directory = "functions"
[build]
  command = "ng build"
  publish = "dist/abc-dashboard/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
  [[headers]]
for = "/.netlify/functions/*"
[headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "*"
  Access-Control-Allow-Headers = "*"