[build]
  publish = "dist"
  command = "ng build --prod"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/mock-api/:splat"
  status = 200
  force = true

[functions]
  directory = "functions"
